### ISSUE TITLE
UserStatistics is missing alot of propeties

### ISSUE THREAD

**Issue by EnricoBaivo** [L-Mario564/osu.js#16]
https://osu.ppy.sh/docs/index.html#userstatistics

<html>
<body>

count_100 | integer |  
count_300 | integer |  
count_50 | integer |  
count_miss | integer

<br class="Apple-interchange-newline">
</body>
</html>

For Example is missing.

**Comment by L-Mario564** [comment]
Added missing properties in latest release.
