### ISSUE TITLE
Types for responses from score related endpoints are not up to date

### ISSUE THREAD

**Issue by yorunoken** [L-Mario564/osu.js#4]
It seems there have been breaking changes made to the API, regarding scores.

**Comment by L-Mario564** [comment]
Checking the official changelog, there doesn't seem to be any breaking changes related to scores. Could you tell me which endpoints are affected? And what's the breaking change in them?

**Comment by yorunoken** [comment]
I'm not completely sure as the change happened when I was outside for work and still am, it's something about the score's structures. 
This is the error I got when I try to execute any score-related command on my Discord bot:
![image](https://github.com/L-Mario564/osu.js/assets/69751661/01c8cbdc-8ab4-46d6-b9da-4dc0326312fd)
`count_geki` and `count_katu` don't seem to exist anymore in osu! gamemode and I'm sure there are a lot more.

**Comment by L-Mario564** [comment]
Taking a look at the docs, the response has definitely changed. There should be a workaround for this using osu.js. Could you share the code you're using to make this request?

**Comment by yorunoken** [comment]
oh uh im actually not using your lib I just thought I'd let you know,
it's the endpoint of getting a user's recent scores

**Comment by L-Mario564** [comment]
Alright, thanks for letting me know.

**Comment by yorunoken** [comment]
Just heard that mod settings are exposed (or have been) in the api now,
https://raw.githubusercontent.com/ppy/osu-web/master/database/mods.json

**Comment by yorunoken** [comment]
Thanks!

**Comment by L-Mario564** [comment]
@YoruNoKen haven't addressed the issue yet, only addressed the new osu! Lazer mods with the latest release.

**Comment by yorunoken** [comment]
oh, I saw you committed a bunch if stuff so I assumed you were done with the types
It's mostly type changes that haven't been documented in api docs, and it undergoes lots of changes rn so i dont know what exactly changes

**Comment by yorunoken** [comment]
@L-Mario564 
btw, the way to get the new structure is by including `x-api-version` like this:

```ts
      resp = await this.fetch(`https://osu.ppy.sh/api/v2/${endpoint}`, {
        method,
        body: options?.body ? JSON.stringify(options.body) : undefined,
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${this.accessToken}`,
          'x-api-version': 20220705
        }
      });
```

**Comment by yorunoken** [comment]
`20220705` is the latest version I could find. If you leave it blank, it returns the old structure.
The structure will probably keep changing, it's been changed a few times already.

**Comment by yorunoken** [comment]
I kinda need it rn because `score` is always `0` in the older structure
