### ISSUE TITLE
Contribution guide

### ISSUE THREAD

**Issue by yorunoken** [L-Mario564/osu.js#8]
Would be great to have a contribution guide to let the contributor what they need

**Comment by L-Mario564** [comment]
@YoruNoKen Just committed the addition of a CONTRIBUTING.md file.
https://github.com/L-Mario564/osu.js/blob/master/CONTRIBUTING.md
Let me know if you have any suggestions to improve it before closing this issue.

**Comment by yorunoken** [comment]
I tried to run `test:auth` 1-2 days ago to get the access token working but it didn't work, so I had to use my own one.
Maybe check if there's a problem there, the issue might just be me though

**Comment by L-Mario564** [comment]
What error did you get? Also, I should probably explain how to do auth related tests in more detail regardless.

**Comment by yorunoken** [comment]
didn't get any errors, when running the auth test. I assume it's supposed to create a .json file with the token keys inside, but it didn't do that, so the other tests fail.

**Comment by L-Mario564** [comment]
Updated CONTRIBUTING.md with a new section about tests.

**Comment by yorunoken** [comment]
Yeah looks good, I'll test it at home, outside rn
